### ISSUE TITLE
Write documentation for outputting auxiliary 2d/3d arrays from the model

### ISSUE THREAD

**Issue by DomHeinzeller** [NOAA-GSL/fv3atm#23]
The capability to output auxiliary 2d/3d arrays (aka "stuff") from the model was added in PR https://github.com/NOAA-GSD/fv3atm/pull/21. We need to write documentation in the appropriate place (ccpp-doc repo?) for it and add a note that for the moment this capability only exists in the NOAA-GSD fork, gsd/develop branch.

@ligiabernardet @julieschramm @climbfuji

**Comment by ligiabernardet** [comment]
Duly noted. Yes, I think the best place is the ccpp-docs. Are there any
draft instructions to start from? Or just the PR itself?

**Comment by climbfuji** [comment]
Yes, in PR #21 there is a comment (https://github.com/NOAA-GSD/fv3atm/pull/21#issuecomment-619252706) how I tested these changes. This contains all the necessary information, I believe, but if there are open questions please let me know. Thanks for helping with writing the documentation ...

**Comment by DomHeinzeller** [comment]
The documentation was added to ccpp-doc.
