### ISSUE TITLE
Rename suite FV3_RAPHRRR to FV3_HRRR

### ISSUE THREAD

**Issue by climbfuji** [NOAA-GSL/fv3atm#29]
Suite `FV3_RAPHRRR` was added in PR https://github.com/NOAA-GSD/fv3atm/pull/28. It needs to be renamed to `FV3_HRRR` for consistency (because it doesn't use convection, which only makes sense at convection-permitting HRRR resolution).

**Comment by DomHeinzeller** [comment]
@tanyasmirnova

**Comment by tanyasmirnova** [comment]
Thank you, Dom.
I wonder if we have to add one more suite FV3_RAP which adds GF convective scheme to physics in FV3_HRRR. Then it will be complete.
Thanks a lot!

**Comment by climbfuji** [comment]
> Thank you, Dom.
> I wonder if we have to add one more suite FV3_RAP which adds GF convective scheme to physics in FV3_HRRR. Then it will be complete.
> Thanks a lot!

We have so many suites and tests already that are doing the same things, or at least almost. We really need to clean this up. The SAR folks are adding more and more suites as well, which is very confusing and overlapping. I'll add the FV3_RAP suite and regression test, but then we need to stop and consolidate all this.

**Comment by tanyasmirnova** [comment]
Dom, I agree that there are too many suites, some of them repeat each other.
I think *SAR* suite has transitioned to the HRRR suite, and could be removed. GSD_v0 suite is the same as RAP suite, although it uses GFS sfc_diff scheme. Mynn_sfc is used in HRRR and RAP suites, and I think that suites with mynn_sfc could be removed. 
Similar thing with gsd_dragsuite. It should become eventually a part of RAP and HRRR suites. 
A question: phys_tend is now only a part of GSD_v0 suite. Should it be added to RAP and HRRR sutes? Any comments from Mike Toy and Joe?

**Comment by climbfuji** [comment]
- phys_tend only needs to be added when turning on ldiag3d and qdiag3d, which should be used only during development; Ligia and Julie are writing documentation on this, once the documentation is completed and merged, we can remove the phys_tend calls from all suites
- drag_suite is, with the next commit (see draft PR https://github.com/NOAA-GSD/ufs-weather-model/pull/25 and references in there), part of the FV3_RAP and FV3_HRRR suites
- let's clean up the suites and regression tests in the next week, before preparing the code for merging to the authoritative repositories

**Comment by climbfuji** [comment]
Suite FV3_RAPHRRR renamed to FV3_HRRR in https://github.com/NOAA-GSD/fv3atm/pull/32. FV3_HRRR is now using the GSL drag suite instead of CIRES UGWP.  Added a new suite FV3_RAP in the same PR, identical to FV3_HRRR but with Grell Freitas convection.
