### ISSUE TITLE
Divide time-integrated tendencies by time for diagnostics output

### ISSUE THREAD

**Issue by grantfirl** [NOAA-GSL/fv3atm#36]
In GFS_diagnostics output, we should be outputting actual tendencies that have rate units, so the accumulated change variables should be divided by (fhzero hours * 3600 seconds) to achieve this.

**Comment by DomHeinzeller** [comment]
@grantfirl I think we fixed this, ok to close the issue?

**Comment by grantfirl** [comment]
I believe that it was fixed with 

ExtDiag(idx)%time_avg = .TRUE.

statements in GFS_diagnostics.F90 for the tendencies terms, so yes.
